baseURL = 'https://chester-232.github.io/'
languageCode = 'en-us'
title = 'JDev Blog'
theme = "beautifulhugo"
# theme = "mainroad"

[markup]
    tasklist = false
    [markup.goldmark]
        [markup.goldmark.renderer]
             unsafe = true